### ISSUE TITLE
Identifikation af hvilke QGIS-projekter som en tabel findes i (et plugin eller program på server)

### ISSUE THREAD

**Issue by MieWinstrup** [Septima/qgis-metadatafunctionality#44]
Denne funktion kan implementeres som et QGIS plugin eller et program der automatisk kører med et specificeret tidsinterval.

Opgaver:
- Lave et særskilt plugin/program, der identificerer hvilke QGIS­projekter/qlr­filer/Spatial Suite temaer en tabel indgår i. Dette skal hjælpe brugerne med at få et overblik over, hvor en tabel indgår og vil vise hvad brugeren skal være opmærksom på, hvis en tabel skal slettes. Denne skal kunne sættes til automatisk kørsel, evt. natlig, hvor samtlige QGIS­projekter/qlr­filer/Spatial Suite temaer gennemgås
- Skal laves så metadata­oplysninger om hvilke projekter de enkelte tabeller indgår i
  automatisk opdateres, så det for hver tabel fremgår hvilke QGIS­projekter denne tabel
  vises.

Tidsestimat: 10-­30 timer ­ det afhænger af kompleksiteten af plugin’et/programmet, bl.a.
Hvorvidt det skal kunne køres både på qgis­projekter og spatial suite eller blot en af disse kilder.

**Comment by mwtishoj** [comment]
@MieWinstrup 
kunne vi gøre det sådan, at vi startede op dette, og koncentrerede os i første omgang på Qgisprojekter og Qlr filer. 
Så kan vi se, hvor langt vi kommer for de første 10 timer. Det vil vi gerne starte med.

**Comment by MieWinstrup** [comment]
Vi overvejet om det skal laves som en udvidelse af qlr-browseren. 

Vores tanker er forsøgt illustreret her: 

![qlr_1](https://user-images.githubusercontent.com/16276034/30748849-d50be248-9fb1-11e7-8faa-9e93c298a8e9.png)

![qlr2](https://user-images.githubusercontent.com/16276034/30748854-d940f45c-9fb1-11e7-8a40-d3739f18e037.png)

![qlr3](https://user-images.githubusercontent.com/16276034/30748858-dcb6a604-9fb1-11e7-9d23-97d7b986a981.png)

**Comment by mwtishoj** [comment]
Vi bruger ikke QLR-browseren, men Spetima Search(S4) til at finde vores filer frem.  Vi vil gerne have, at info omkring hvilke projekter, nogle bestemte filer bliver brugt i tilføjes metadata på det enkelte tema(fil), som vi har i vores metadatabase. 

Hvis det på en enkelte måde kan laves, så det sker automatisk, når den har kørt programmet igennem via Qlr- browseren, så kan funktionen godt lægge i den.  Det kunne måske være sådan, at man satte hak et sted i Qlr browseren, om metadata skulle opdateres, og den pegede til databasen. 

Hvordan tænker I, at det kunne virke? Ellers lad os tage et telefonmøde omkring det

Vi kunne også på sigt at kunne få vi det som du har i Qlr - browseren i S4.

**Comment by MieWinstrup** [comment]
Denne søgning er implementeret i Septima Search.
