### ISSUE TITLE
Kunne slette en linje i tabellen Metadata

### ISSUE THREAD

**Issue by mwtishoj** [Septima/qgis-metadatafunctionality#61]
Jeg ville gerne rydde op i min metadatatabel, men jeg kan ikke få lov til at slette en linje i tabellen, hverken fra PGadmin eller qgis. 

hvordan sletter jeg en linje ?

**Comment by MieWinstrup** [comment]
@mwtishoj, så du kan ikke få slettet de ønskede rækker i metadatatabellen i PgAdmin ved at gøre følgende:
1. højreklik på tabellen --> View data --> View top 100 rows
2. Vælg rækker der skal slettes (ctrl for valg af flere rækker).
3. Højreklik på yderste række (med tal) og vælg 'Delete'

?

**Comment by mwtishoj** [comment]
Hej Mie

Jeg kan ikke slet, som du har beskrevet.

Som jeg kan se det, så er jeg logget på med k183 rettigheder, og skulle derfor have rettigheder til at slette, men det har jeg desværre ikke.

Med venlig hilsen

Mik Wulff Thomsen
GIS- og Geodata specialist, MTM Geoinformatik / Teamleder

Direkte

43 57 77 60

Mobil

30 92 18 51

Email

MWT@ishoj.dk<mailto:MWT@ishoj.dk>





[http://www.ishoj.dk/maillogo/ishojkommune_byvaben.jpg]


Ishøj Kommune


Planlægning administration
Baldersbækvej 6
2635 Ishøj
Telefon 43 57 75 75
webkort.ishoj.dk<http://ishoj.dk>




Fra: Mie Winstrup [mailto:notifications@github.com]
Sendt: 21. november 2016 13:41
Til: Septima/qgis-metadatafunctionality
Cc: Mik Wulff Thomsen; Mention
Emne: Re: [Septima/qgis-metadatafunctionality] Kunne slette en linje i tabellen Metadata (#61)


@mwtishoj<https://github.com/mwtishoj>, så du kan ikke få slettet de ønskede rækker i metadatatabellen i PgAdmin ved at gøre følgende:

  1.  højreklik på tabellen --> View data --> View top 100 rows
  2.  Vælg rækker der skal slettes (ctrl for valg af flere rækker).
  3.  Højreklik på yderste række (med tal) og vælg 'Delete'

?

**Comment by MieWinstrup** [comment]
Får du en besked/fejlbesked?

**Comment by mwtishoj** [comment]
Nej.. der er ingen fejlbesked, kun at jeg ikke kan vælge, hvilken copy, past, eller delete, de er bare grå.

Jeg har også forsøgt, at åbne tabellen i Qgis og gøre den rediger bar, også her får jeg ikke muligheden for at slette en linje.

**Comment by MieWinstrup** [comment]
Hvem er ejer af metadata-tabellen? 
![image](https://cloud.githubusercontent.com/assets/16276034/20484444/76b2ddbe-aff7-11e6-967f-ebc7dd9ad815.png)

**Comment by mwtishoj** [comment]
![metadata-sletning](https://cloud.githubusercontent.com/assets/4126030/20484562/fa5e8cc6-aff7-11e6-813a-967e5e8157c4.jpg)

**Comment by mwtishoj** [comment]
![metadata-sletning2](https://cloud.githubusercontent.com/assets/4126030/20484620/495fcd1c-aff8-11e6-8b4c-e5fe9887a39e.jpg)

**Comment by MieWinstrup** [comment]
Og hvilken databaseusername er indtastet i metadata-db-linker-settingsdialog?

![image](https://cloud.githubusercontent.com/assets/16276034/20485425/c53dea38-affb-11e6-900b-f3acc44886f1.png)

**Comment by mwtishoj** [comment]
![metadata-sletning3](https://cloud.githubusercontent.com/assets/4126030/20485492/0bbd3342-affc-11e6-8afc-9148752a9237.jpg)

**Comment by mwtishoj** [comment]
Hvad er status @MieWinstrup, kan vi lave noget der, så vi kan slette linjer?

**Comment by mwtishoj** [comment]
@MieWinstrup @klavspc  Kan I give en status på denne opgave?

**Comment by MieWinstrup** [comment]
Løst :)
