### ISSUE TITLE
Fremsøgning af data via S4 fra metadataDB

### ISSUE THREAD

**Issue by mwtishoj** [Septima/qgis-metadatafunctionality#63]
Jeg synes, det er lidt underligt, at når jeg i S4gis, skriver "vandl" så finder den 10 stk, men skriver jeg "vandløb", så finder den ingen, og der er mange mindst 5 stk. 

Jeg tror årsagen er "Æ;Ø;Å", så fejler den. 

Kan vi finde en løsning
![s4_vandl_fejl_10stk](https://user-images.githubusercontent.com/4126030/27675061-b92a68de-5ca8-11e7-967b-d0c932bd801c.jpg)
![s4_vandlob_fejl_0stk](https://user-images.githubusercontent.com/4126030/27675060-b927bc06-5ca8-11e7-8dec-363e115775ed.jpg)

**Comment by mwtishoj** [comment]
Det virker fint ;)

**Comment by MieWinstrup** [comment]
Fixet med version v0.1.6. Dette issue lukkes.
