### ISSUE TITLE
Porteres til QGIS3

### ISSUE THREAD

**Issue by MieWinstrup** [Septima/qgis-metadatafunctionality#64]
Koden til pluginet skal ændres fra Python 2 til Python 3.
Det meste af koden ser ud til at kunne konverteres relativ let, men interaktionen med DB-Manager kan potentielt skabe lidt udfordringer. I forbindelse med konverteringen vil det være nødvendigt med lidt oprydning af koden.

**Comment by kthy** [comment]
Er det her issue WIP eller bare på ønskelisten? :)

**Comment by henrikhedelund** [comment]
Det er noget vi gerne vil have lavet inden længe, da det virkelig er noget vi savner i QGIS3...

**Comment by henrikhedelund** [comment]
...jeg regner med at du lige koordinerer/aftaler med Mie, da hun for nogle uger siden var her i Ishøj og havde en snak med Felipe om bl.a. dette plugin

**Comment by henrikhedelund** [comment]
Hej Kristian
vi (Ishøj Kommune) har financieret førsteudgaven af pluginnet, og vi er super glade for det, som det har kørt på 2.x versionerne af QGIS.
Vil I være med til at spæde i kassen til 3.x udgaven?
I er velkomne til at kontakte os for at høre om vores erfaringer

**Comment by NicolaiMogensen** [comment]
Fixed in pull #69
