### ISSUE TITLE
Indstillinger til pluginet være i de generelle indstillinger

### ISSUE THREAD

**Issue by MieWinstrup** [Septima/qgis-metadatafunctionality#65]
I pluginet til QGIS 2 laves indstillingerne til pluginet under pluginet i menuen 'plugins':
![MetadataDbLinker-Settings_QGIS2 18](https://user-images.githubusercontent.com/16276034/58316460-e4d2a800-7e13-11e9-8906-beb3f611c2b4.png)

I pluginet til QGIS 3 skal disse indstillinger istedet laves i den generelle indstillingsmenu, hvor der skal tilføjes en fane til pluginet (ligesom der er til GeosearchDK og Kortforsyningen):
![MetadataDbLinker-Settings](https://user-images.githubusercontent.com/16276034/58316356-a3da9380-7e13-11e9-9acd-6b55183a9f15.png)

**Comment by NicolaiMogensen** [comment]
Fixed in pull #69
